# Generated by Django 5.1 on 2024-08-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banks',
            field=models.ManyToManyField(related_name='users', to='banks.bank'),
        ),
    ]
