# Generated by Django 5.1 on 2024-11-25 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
