# Generated by Django 5.1 on 2024-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditanalysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10),
        ),
    ]
